permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  network_key:
    - 43
    - 135
    - 43
    - 15
    - 137
    - 122
    - 86
    - 131
    - 201
    - 239
    - 196
    - 93
    - 130
    - 111
    - 103
    - 144
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x2c1165fffe85f881':
    friendly_name: LightPatio
    description: IKEA Trader bulb on Patio, reset by 7 x off/on cycles
