permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
homeassistant: true
advanced:
  network_key:
    - 43
    - 135
    - 43
    - 15
    - 137
    - 122
    - 86
    - 131
    - 201
    - 239
    - 196
    - 93
    - 130
    - 111
    - 103
    - 144
  homeassistant:
    discovery_topic: homeassistant
    status_topic: hass/status
    legacy_entity_attributes: true
    legacy_triggers: true
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x2c1165fffe85f881':
    friendly_name: LightPatio
    description: IKEA Trader bulb on Patio, reset by 7 x off/on cycles
  '0xa4c1386153591ed2':
    friendly_name: LightLoungeStriplight
    description: the miboxer strip light in the huge, press button to reset
